### ISSUE TITLE
Prevent the wires & components from automatically connecting too eagerly

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-basics#1]
One of our research colleagues suggested:

Last Friday, we met in our PhET group, discussing studies we currently run that involve PhET simulations. During that meeting, we also discussed problems we encountered in the usability of the DC CCK simulation. I write you to explain you the problem, and ask whether you have addressed this problem already, if so how (in light of the HTML5 iteration), and if not, what you think would be required to fix the issue. 

The problem we discussed is the "stickiness" of the ends of not yet placed wires. Here is an example scenario: You have a certain partial circuit already built. You drag an additional wire connection into the screen that you would like to attach to a particular connection. However, while dragging it across the screen, the ends of the wire get temporarily attached to the closest existing junction of the circuit. That by itself might not be problematic, and actually rather useful. The issue is more that the "attraction radius" of each junction is pretty big, such that in not even too cluttered circuits it is almost impossible to place a wire without having it connect to anything automatically. This makes the interaction with the system more difficult, and is problematic particularly for users with less experience of working with the simulation. 

Have you already addressed that problem in the next iterations of the CCK? Would it be possible to adapt the current version of the CCK to fix that issue? Is there an "attraction radius" parameter that one could change without too much work, or is it rather complicated to change it in the current CCK version?

Thanks for your information and help!

**Comment by samreid** [comment]
I reduced the attraction radius significantly, in Java it is >4 radii and in this version of CCK it is 1 radius, which seems to be a good user experience:

http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-basics/1.0.0-dev.2/circuit-construction-kit-basics_en.html

@arouinfar can you review this issue and comment?  Also, I believe the suggestion was from Engin--I'll let you decide if and when you want to discuss this with Stanford over email/in a meeting/etc.

**Comment by arouinfar** [comment]
@samreid I somehow looked over this issue. Sorry for the delayed response.

I think the snappy-ness of 1 radius feels great, and I definitely prefer it to >4 radii. I can show this feature to Stanford next time I chat with them, but I think this issue can closed for now and reopened if it needs tweaking.
