### ISSUE TITLE
Use the bulb artwork from Faraday's Law or scenery-phet

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-basics#11]
@arouinfar said:

> For CCKB we should use the bulb from Faraday’s Law and the ray-glow from Acid-Base Solutions.

**Comment by samreid** [comment]
Note there is a near-duplicate in Capacitor Lab Basics.

**Comment by samreid** [comment]
@jbphet and @jessegreenberg how should I approach this issue?

**Comment by samreid** [comment]
See https://github.com/phetsims/scenery-phet/issues/170 for details about consolidating Light Bulb graphics.

**Comment by jbphet** [comment]
Ideally, we would attempt to come up with a common code version with variations of bulbs and rays that satisfied all needs.  A bulb with rays will also be needed for the Energy Forms and Changes sim.

**Comment by samreid** [comment]
I discussion with @jessegreenberg today, we decided I can use the scenery-phet bulb (looks like acid base solution, but has rays) then wait for discussion with designers about whether we can upgrade that one to look like the faraday's law one.

**Comment by samreid** [comment]
The sim is using the scenery-phet light bulb now, except for the toolbox icon.  After the toolbox icon is switched to use the common code, we can close this issue.
