### ISSUE TITLE
Add a placeholder for tap circuit element to edit

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-basics#15]
From today's meeting:

Have placeholder text in a simple panel “tap circuit element to edit” once you tap slider appears with trash button for deleting component. Any other interaction removes the edit panel.

Halo for indicating for which component is being edited. Simple yellow outline to suggest the thing you are editing.  Icon in the slider area.

**Comment by samreid** [comment]
@phetsims/dubson votes against the icon in the control panel.

**Comment by samreid** [comment]
@ariel-phet @arouinfar @kathy-phet @phetsims/dubson Thinking this through, it seems plausible that some students will read the text "tap circuit element to edit" and try to tap on a circuit element while it is still in the toolbox.  Maybe we should only show this text when there is >=1 circuit element in the play area.

**Comment by arouinfar** [comment]
Good point @samreid. Requiring >=1 element seems like a reasonable solution to me.

**Comment by ariel-phet** [comment]
:+1:

**Comment by samreid** [comment]
Fixed for dev.2, closing.
