### ISSUE TITLE
Make resitors more tan

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-basics#19]
@ariel-phet said:

> Resistors also tend to be more "tan" http://images.wisegeek.com/tan-fixed-resistors.jpg

**Comment by samreid** [comment]
From our sim:
![image](https://cloud.githubusercontent.com/assets/679486/14047527/e21ff5b6-f26d-11e5-8fb9-063856dfe199.png)

From the image @ariel-phet linked:
![image](https://cloud.githubusercontent.com/assets/679486/14047541/f02d54c8-f26d-11e5-96d3-a829fdf8664e.png)

**Comment by samreid** [comment]
I sampled colors from the linked image, now it looks like this:
![image](https://cloud.githubusercontent.com/assets/679486/14047732/385aabdc-f26f-11e5-885e-60e6b744b911.png)

I'm also making the resistor slightly more bulbous:
![image](https://cloud.githubusercontent.com/assets/679486/14047860/0db6ac72-f270-11e5-9af1-c940319f0ec7.png)

**Comment by samreid** [comment]
@ariel-phet can you take a look?

**Comment by ariel-phet** [comment]
@samreid I think they need to go even more "tan" than that for good differentiation (but could work as is). Your call if you want to spend more effort. I would try the brighter tan tones sampled from the left side of the image (near where it necks down).

**Comment by samreid** [comment]
I sampled from the neck on the left side and it seems a bit bright to me:

![image](https://cloud.githubusercontent.com/assets/679486/14082622/46441092-f4ce-11e5-91fe-ed3d73af6802.png)

**Comment by ariel-phet** [comment]
I would try #DEB887 as the base color

**Comment by samreid** [comment]
I tried to go halfway between the last two images, and it seems much better:

![image](https://cloud.githubusercontent.com/assets/679486/14082726/c9470c10-f4ce-11e5-9c7c-02ffbad6c030.png)

Pushing shortly for review.

**Comment by samreid** [comment]
For reference, the above image is #deb47d, not too different from #DEB887

**Comment by ariel-phet** [comment]
No worries, I suggested that hexcode before seeing your next comment

**Comment by samreid** [comment]
This is #DEB887, I'm fine with either.

![image](https://cloud.githubusercontent.com/assets/679486/14082810/4ede77c8-f4cf-11e5-8b18-6a82c6038f42.png)

Pushing shortly...

**Comment by samreid** [comment]
Pushed #DEB887 above, please pull master and review.

**Comment by ariel-phet** [comment]
@samreid looking good. One other minor point...can we make the "bands" match the diameter of the resistor more closely. I find the fact that the stick out so much distracting when I change the resistance.

**Comment by samreid** [comment]
> One other minor point...can we make the "bands" match the diameter of the resistor more closely. I find the fact that the stick out so much distracting when I change the resistance.

Sure, we'll track that in #41
