### ISSUE TITLE
Graphics needed for Light Bulb, Battery, etc.

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-basics#2]
The simulation will soon be to a point where it will benefit from artwork for the light bulb, battery, etc.  For now, I've copy pasted from the design doc raster, but they are pretty grainy and low resolution.  @arouinfar can you help?

**Comment by arouinfar** [comment]
I've emailed assets for the batteries, wire, and voltmeter to @samreid.

The light bulb should be the one used in Capacitor Lab: Basics and Faraday's Law. It's being moved to scenery by @jessegreenberg. I'm not sure if that's happened yet, but for the bulb from Acid-Base Solutions should already be in scenery. I'm fine with that one being used as a placeholder.

**Comment by samreid** [comment]
I committed the artwork in 30b6e158ff5e54687e9825de6650f97c0fa0cb08 and will unassign the issue until it is time to finish integrating the artwork and using the appropriate light bulb.

**Comment by jessegreenberg** [comment]
The light bulb hasn't been generalized yet, but that will be the next thing for capacitor-lab-basics.

**Comment by samreid** [comment]
I've got all of the raster graphics and am using scenery-phet's light bulb, closing.
