### ISSUE TITLE
Solder layering is inconsistent

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-basics#20]
@ariel-phet said:

> The layering of the "solder joint" is not consistent (I think it should always be behind other circuit elements). For instance it looks particularly odd when in covers the battery ends

**Comment by samreid** [comment]
Yes, it is odd when the solder covers a battery:

![image](https://cloud.githubusercontent.com/assets/679486/14047465/7887b6d4-f26d-11e5-91ea-fdc849a22a2e.png)

Here's what it looks like with solder and dotted line behind the battery:

![image](https://cloud.githubusercontent.com/assets/679486/14047483/90b4e434-f26d-11e5-960a-0bee3a01c0e9.png)

Is there any chance we'll want the dotted line in front of the battery, but the solid solder behind the battery?  Any part of the circle that is obscured by the battery would be clicked as "battery" instead of "vertex", is this as desired?  @arouinfar or @ariel-phet please let me know your thoughts.

**Comment by samreid** [comment]
Another question: is it OK if the yellow vertex highlight is in the back?

![image](https://cloud.githubusercontent.com/assets/679486/14057557/415ca618-f2c9-11e5-90a1-19fa349a6a83.png)

**Comment by samreid** [comment]
Having the junctions always in the back makes tapping a vertex difficult in this case:

![image](https://cloud.githubusercontent.com/assets/679486/14057586/f817ff92-f2c9-11e5-8968-2b21ffc8f426.png)

**Comment by samreid** [comment]
In the java, the dotted line is always in front and hence always selectable, but the solder is always behind

![image](https://cloud.githubusercontent.com/assets/679486/14060654/da753fce-f330-11e5-9f99-9f026852c597.png)

![image](https://cloud.githubusercontent.com/assets/679486/14060656/ea6aea8c-f330-11e5-9b35-cf8563d46b62.png)

**Comment by samreid** [comment]
Pic of a wire wire battery vertex:
![image](https://cloud.githubusercontent.com/assets/679486/14060727/e01b5af6-f332-11e5-93f7-d8f6414fa004.png)

**Comment by samreid** [comment]
So the desired behavior is:
1. silver solder behind all wires and components
2. copper circle in front of wires but behind components
3. dotted line in front of all wires and components
4. highlight in front of all wires and components

**Comment by samreid** [comment]
> 2. copper circle in front of wires but behind components

This might be solved with a round instead of square cap for the line segments.

**Comment by samreid** [comment]
![image](https://cloud.githubusercontent.com/assets/679486/14060784/83b5cde4-f334-11e5-9bf9-41d149c62551.png)

Round caps seem good.

**Comment by samreid** [comment]
> (4). highlight in front of all wires and components

this will come naturally if we moveToFront on selection

**Comment by samreid** [comment]
After the above changes, solder is in back, vertices are in front, @ariel-phet can you pull master and take a look?

![image](https://cloud.githubusercontent.com/assets/679486/14062403/15f4ebee-f363-11e5-9e02-3b09ee3d135c.png)

**Comment by ariel-phet** [comment]
@samreid - current pull of master is not showing solder connections, and connections are just breaking when I move a vertex point?

**Comment by samreid** [comment]
Is this what you are seeing?

![touch](https://cloud.githubusercontent.com/assets/679486/14084290/464e5ddc-f4d7-11e5-9479-ed23ff7c9ee3.gif)

**Comment by ariel-phet** [comment]
Nope...when I "attach" no background silver solder is formed, and when I drag the vertex as you do at a connection, it just splits.

**Comment by ariel-phet** [comment]
(testing on chrome by the way)

**Comment by samreid** [comment]
Clear cache?  Incognito mode?  Make sure all your repos pulled?  I'll also publish a dev version in case there's a problem on your side that you cannot easily overcome.

**Comment by samreid** [comment]
Please test this version and report back:

http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-basics/1.0.0-dev.4/circuit-construction-kit-basics_en.html

**Comment by ariel-phet** [comment]
Same issues seen on that dev version (tested both chrome and FF)

**Comment by arouinfar** [comment]
I'm also seeing the same issues as @ariel-phet in Chrome.

**Comment by arouinfar** [comment]
It's the same in Safari too. When the nodes get attached, there is no soldering visible, and node can be broken by dragging the wires away from the vertex. Clicking on nodes does not reveal the scissors, and tapping to edit an element appears to be broken as well.

**Comment by samreid** [comment]
I can reproduce the problem now, I'll look into it.

**Comment by samreid** [comment]
Fixed in the above commit, master should be OK now and I published dev.5 here:
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-basics/1.0.0-dev.5/circuit-construction-kit-basics_en.html

Reassigning to @ariel-phet to take a look.

**Comment by ariel-phet** [comment]
@samreid layering looks good. I would suggest making the solder "blob" a bit smaller (20 percent or so) but keeping the dotted line as is. Right now the blob just feels a bit heavy handed and I think some more negative space between the blob and dotted line will be beneficial.

**Comment by samreid** [comment]
In the above commit I reduced the radius by 20%, and it looks like this:

![image](https://cloud.githubusercontent.com/assets/679486/14085931/d5d75eba-f4df-11e5-80b2-c1f13607dc1b.png)

@ariel-phet please pull and review

**Comment by ariel-phet** [comment]
I find that look to be an improvement, Closing

**Comment by arouinfar** [comment]
Great suggestion @ariel-phet. I think the nodes look much cleaner in @samreid's screenshot.
