### ISSUE TITLE
Move scissors closer to the node

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-basics#23]
@ariel-phet said:

> The scissors appear quite far from the joint you wish to split, it seems they could be closer for clarity (not a big deal)

**Comment by samreid** [comment]
Before, with DISTANCE_TO_CUT_BUTTON = 100:

![image](https://cloud.githubusercontent.com/assets/679486/14046537/cf0edc04-f267-11e5-8140-426b0649ec39.png)

After, with DISTANCE_TO_CUT_BUTTON = 70:

![image](https://cloud.githubusercontent.com/assets/679486/14046608/0d71e0f4-f268-11e5-95a5-0f039b44c39a.png)

**Comment by samreid** [comment]
@ariel-phet please review

**Comment by ariel-phet** [comment]
Looks much better to me. Closing
