### ISSUE TITLE
Bulb should connect at the bottom and side

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-basics#26]
From the design doc:

![image](https://cloud.githubusercontent.com/assets/679486/14060864/af6e7d30-f336-11e5-8ca6-e8bc2b1f1f50.png)

@arouinfar is this essential for minimum viable product for Stanford?

**Comment by samreid** [comment]
The current bulb connections look like this:

![image](https://cloud.githubusercontent.com/assets/679486/14060869/dc5b16f0-f336-11e5-9928-9057f5d2a23d.png)

**Comment by samreid** [comment]
Oops solder was commented out in the last photo, here is the latest:

![image](https://cloud.githubusercontent.com/assets/679486/14060874/fb7f3764-f336-11e5-8206-a6d0a571aec1.png)

**Comment by arouinfar** [comment]
@samreid this is something I can run past Stanford. My best guess is that having the appropriate bottom/side connections for the light bulb is going to be important, as most introductory physics courses will emphasize these connections. An alternative would be to put the light bulb in a socket to obscure the terminals of the bulb.

**Comment by arouinfar** [comment]
@kathy-phet suggested
> Re the bulb - I would suggest a new image that show the same connection arrangement as the original cck.
![image](https://cloud.githubusercontent.com/assets/8419308/14430641/a3dc77ac-ffbf-11e5-84a1-914afb544a24.png)

Currently, we are using the scenery bulb. Eventually the solder blob will be layered above the wire (#48) though this is not a required feature for the MVP. There has been lengthy discussion over the use of this bulb in https://github.com/phetsims/scenery-phet/issues/170
![image](https://cloud.githubusercontent.com/assets/8419308/14430527/32422f60-ffbf-11e5-8d22-fd22faf06b39.png)

This bulb style has appeared in Acid-Base Solutions and EFAC. Neither shows how the filament attaches to the bulb, though the Acid-Base Solutions bulb has an appropriate connection. EFAC appears to be leveraging the socket representation.
![image](https://cloud.githubusercontent.com/assets/8419308/14430499/10af18d6-ffbf-11e5-9006-be454c805c85.png)![image](https://cloud.githubusercontent.com/assets/8419308/14430775/213fa174-ffc0-11e5-8362-70833f932152.png)

There is an different bulb style used in Capacitor Lab: Basics and Faraday's Law. Both show the bottom-side connections, but do not show the exact path of the filament. This bulb style will not be ideal when it comes time to show the electrons traveling through the filament.
![image](https://cloud.githubusercontent.com/assets/8419308/14430799/3c7a35f8-ffc0-11e5-8c9a-4b91e2650bf0.png)![image](https://cloud.githubusercontent.com/assets/8419308/14430828/507195d8-ffc0-11e5-9fbc-ae34418ef72b.png)

If we create a new bulb that matches the Java CCK, we will no longer be using a scenery/common component, and we will be introducing yet another bulb style to our HTML5 sims.  The MVP does not include the electron representation, so I think it's less necessary to show the exact filament bath (as we do in Java). I think the best option would be to move one of the light bulb nodes to the bottom.

@samreid how feasible would it be to move one of the nodes of the bulb we're currently using to the bottom?

**Comment by samreid** [comment]
So it would look like this?

![image](https://cloud.githubusercontent.com/assets/679486/14763361/c96e5b12-0950-11e6-90dc-5d1019f67020.png)

In the Java one I recall a feature to toggle the connection side for the light bulbs.  Are we doing that for the HTML5 one?  If so, should it appear in the light bulb edit panel at the bottom of the screen (which appears when the light bulb is tapped)?

**Comment by arouinfar** [comment]
@samreid that looks good. We can discuss the toggle in design meeting, but it's not necessary for the MVP. The light bulb edit panel seems like a logical place to put it. 

Can you comment out the code for the side connection? That way we can add it back later.

**Comment by samreid** [comment]
I didn't implement it yet, the pic above is a mockup.

> Can you comment out the code for the side connection? That way we can add it back later.

I'm confused.  Is the side connection not necessary for MVP?

**Comment by arouinfar** [comment]
Ah, I misinterpreted your earlier comment @samreid. I thought you had implemented the bottom/side connection. My bad!

Bottom/side connection is preferred for MVP. How much work would it take to switch the connections? The bulb artwork would stay the same. We wouldn't add the connection toggle to the MVP, but it would nice to keep the code somewhere if we decide to add that functionality to future versions.

**Comment by samreid** [comment]
> How much work would it take to switch the connections? 

Probably half a day for the initial implementation, then a bit of scattered time for maintenance.  Since switching the connections is not necessary for MVP, I'll create a new, regular priority issue.

**Comment by samreid** [comment]
I moved the bulb connection points above, it should be reviewed.

**Comment by samreid** [comment]
Here's the latest snapshot of the implementation:
![image](https://cloud.githubusercontent.com/assets/679486/14768036/2f03375c-09f3-11e6-9f7c-1e1c76ff7c0e.png)

**Comment by samreid** [comment]
New bulb is visible here, @arouinfar can you take it for a test drive?
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-basics/1.0.0-dev.7/circuit-construction-kit-basics_en.html

I'm aware the implementation differs from the mock-up a bit (different side and connection points closer to the bulb), but this was a bit simpler.  Let me know if changes are necessary for MVP or desired for future versions.

**Comment by arouinfar** [comment]
@samreid I think the screenshot looks good. Moving the nodes to simplify the implementation seems reasonable to me. 

I will play with the dev version later and get back to you. Thanks!

**Comment by arouinfar** [comment]
Dev version feels good @samreid!

**Comment by arouinfar** [comment]
From 5/27 meeting with Stanford:

This bulb is fine for Black Box studies. For more general studies with CCK it would be better to update the artwork to show a clear connection.
![image](https://cloud.githubusercontent.com/assets/8419308/15621070/9598bd56-241b-11e6-900d-7962d8761af9.png)
