### ISSUE TITLE
New drag behavior for the terminals of fixed length components

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-basics#3]
In Java's CCK there is a fundamental difference between how wires and other fixed-length components such as light-bulbs, batteries, etc can be used.  A battery cannot be connected to a terminal by rotating it--only by dragging it.  This is asymmetric to the drag behavior in wires, which can be connected by dragging the wire body or the wire terminals.

I think it will make the simulation easier to use if you can connect batteries (or other fixed-length components) by dragging their terminals and the only reason the Java CCK doesn't have a behavior like this is that we couldn't think of one at the time.  I tried one strategy for solving this while I was working on the battery drag handler, but it seems different enough that I wanted to run it past the rest of the team @arouinfar @ariel-phet @kathy-phet before deciding one way or another.  I'll paste a movie here that shows the behavior (unfortunately too many quirks at the moment to publish a dev version).  Not pictured in the movie: the battery would also have the "snapping" behavior other components do.

![dragbat3](https://cloud.githubusercontent.com/assets/679486/10570904/763fea8e-75f6-11e5-8a23-52a7f1a58b24.gif)

**Comment by arouinfar** [comment]
I really like this interaction @samreid. It seems very natural! Let's discuss it at the next design meeting (possibly 10/29 -- KP is out, definitely 11/5) to see what @kathy-phet and @ariel-phet think.

**Comment by samreid** [comment]
Consensus at the Nov 12 meeting was that we should pursue this type of interaction--it looks good.

**Comment by arouinfar** [comment]
Reassigning to @samreid for implementation.

**Comment by samreid** [comment]
I'll work on this when I get back to CCK, unassigning for now.

**Comment by samreid** [comment]
Implemented in dev.2 and working nicely, even when circuit elements are attached to groups, closing.
