### ISSUE TITLE
How should black box interface vertices work?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-basics#38]
In master, black box vertices lie on the edge of the box and can be connected internally or externally like so:

![image](https://cloud.githubusercontent.com/assets/679486/14063735/bbb3e5f2-f39b-11e5-82f2-380b2496864d.png)

![image](https://cloud.githubusercontent.com/assets/679486/14063736/c070f30a-f39b-11e5-85e2-8386e30c7d53.png)

In the design doc, there is a wire adapter across the black box interface like so:

![image](https://cloud.githubusercontent.com/assets/679486/14063739/d0adaeb6-f39b-11e5-9819-8ed977c4d18e.png)

![image](https://cloud.githubusercontent.com/assets/679486/14063741/d83fedba-f39b-11e5-8355-04f700d7a604.png)

@arouinfar can you comment on why you proposed the wire adapter across the black box interface, and your thoughts on the single interface vertex (from a user interface point of view)?

**Comment by arouinfar** [comment]
@samreid the mockup was based on the Java CCK: Black Box which had wires sticking out from behind the black boxes. 

I don't see any reason why the vertices can't sit on the edge of the black box, as you've done in master. Actually, I think it looks a lot cleaner that way!

Reassigning to @samreid to implement/close as necessary.

**Comment by samreid** [comment]
OK I'll continue with single vertices, closing.
