### ISSUE TITLE
'grunt published-README' was not run in 1.0 branch

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/circuit-construction-kit-basics#4]
The 1.0 branches of the this sim still indicates that the sim is unpublished.

The master checklist for sims says:

> - [ ] README.md updated using `grunt published-README` (in master and release branch)

**Comment by pixelzoom** [comment]
This appears to be a problem with `grunt production`.  It runs `grunt published-README` in master, but not in the release branch.

**Comment by samreid** [comment]
General problem addressed in https://github.com/phetsims/chipper/issues/698

**Comment by samreid** [comment]
This sim "basics" *is* unpublished, closing.

**Comment by pixelzoom** [comment]
Mea culpa.
