### ISSUE TITLE
Can we make the "bands" match the diameter of the resistor more closely?

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-basics#41]
From #19, @ariel-phet said:

> One other minor point...can we make the "bands" match the diameter of the resistor more closely. I find the fact that the stick out so much distracting when I change the resistance.

**Comment by samreid** [comment]
Fixed above, looks like this now:

![image](https://cloud.githubusercontent.com/assets/679486/14132088/e5fb7c02-f5fe-11e5-8ce4-1096b128d2d9.png)

@ariel-phet review if you wish.

**Comment by ariel-phet** [comment]
Much better, closing
