### ISSUE TITLE
Add some gradient on the wire to make it look "shiny"

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-basics#42]
From #18 

@ariel-phet said:
> I have to say...if possible, I think it would be good to have some gradient on the wire to make it look "shiny" would be nice. Perhaps a color closer to the "copper" end of the battery? Again, I know this is the realm of pixel polishing, but seems valuable since students apparently needed to differentiate wire and resistor more.

**Comment by samreid** [comment]
I added a wire gradient in the above commit.  It is asymmetrical, and hence there is an angle at which the gradient flips.  I will need to ask @arouinfar and @ariel-phet if that is too distracting.  If so, we can try for a symmetrical gradient (or more subtle gradient) that doesn't need to flip.  But first I need to fix the highlight region.

**Comment by samreid** [comment]
Highlight fixed above.  The new gradient looks like this:

![image](https://cloud.githubusercontent.com/assets/679486/14133180/42b52596-f60a-11e5-9b61-c193f44af042.png)

@ariel-phet and @arouinfar please take a look and recommend changes.  You can also pull master to try it out or let me know if you'd like a published dev version.

**Comment by ariel-phet** [comment]
@samreid this definitely looks much more like a wire to me.

One suggestion I would have (but it is definitely not necessary for MVP) is to layer the solder blob above the wire, but below all other components. I think that would tend to make wire joints look nicer. But that would purely be an aesthetic change.

**Comment by ariel-phet** [comment]
assigning to @arouinfar for her opinion

**Comment by samreid** [comment]
This issue is about "Add some gradient on the wire to make it look "shiny"", which @ariel-phet approved in this comment: https://github.com/phetsims/circuit-construction-kit-basics/issues/42#issuecomment-203475993

Layering the solder blob above the wire is a separate issue, so I'll close this issue and create a new issue.

**Comment by arouinfar** [comment]
I think the gradient looks good @samreid!

**Comment by arouinfar** [comment]
@samreid since you've added a gradient to the wire, the icon in the toolbox should also be updated to match.  Currently, the wire segment in the toolbox is a simple stroke.
![image](https://cloud.githubusercontent.com/assets/8419308/14156324/0dd4987e-f683-11e5-8475-caecad5d8211.png)

**Comment by samreid** [comment]
Updated in the toolbox:
![image](https://cloud.githubusercontent.com/assets/679486/14162489/8738834e-f6a9-11e5-9431-845000c8980f.png)

and Screen icon:
![image](https://cloud.githubusercontent.com/assets/679486/14162498/909ebdae-f6a9-11e5-81ae-47b7d1a5e547.png)

@arouinfar please take a look and let me know your thoughts.

**Comment by arouinfar** [comment]
Looks good, thanks! Closing.
