### ISSUE TITLE
Black box obscures external circuit elements

### ISSUE THREAD

**Issue by andrewadare** [phetsims/circuit-construction-kit-basics#44]
Z-ordering puts black box on top. Should this be changed?

![image](https://cloud.githubusercontent.com/assets/154163/14116860/22d30cb8-f59f-11e5-9f75-d30c39d0bdb4.png)

**Comment by samreid** [comment]
Likewise, the voltmeter is going behind the black box:

![image](https://cloud.githubusercontent.com/assets/679486/14131617/6c6b0e42-f5fa-11e5-8357-d1459a981820.png)

**Comment by samreid** [comment]
Fixed above by interleaving the black box node in the circuit nodes, will need testing since now we run the risk of an operation putting the black box circuitry in front.

**Comment by samreid** [comment]
Fixed one error case above.  Others should be reported in new issues, closing.
