### ISSUE TITLE
Objects placed outside of the dev bounds can get lost when the window resized

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-basics#53]
Objects placed outside of the dev bounds can get lost when the window resized

@arouinfar and @ariel-phet how would you recommend to address this problem?

![devbounds](https://cloud.githubusercontent.com/assets/679486/14164553/c0351cfc-f6bd-11e5-8687-38015f1de4e0.gif)

**Comment by samreid** [comment]
I guess we could use the following algorithm:

when window resized:
for each vertex
if vertex out of visible bounds
  translate vertex and connected subgraph of circuit into bounds

This algorithm wouldn't know how to move circuit elements back where they came from, say if an iPad went from landscape => portrait => landscape again.

**Comment by arouinfar** [comment]
@samreid we dealt with a similar issue in Charges & Fields. Charges placed outside of dev will scoot with the edge of the window until the center of the charge is on the dev boundary. If the window is then expanded, the charge remains in place. I think this would be a good approach to take in CCK.


![caf_scoot](https://cloud.githubusercontent.com/assets/8419308/14183492/d759edca-f72d-11e5-87eb-ffb2d96e1b6d.gif)

**Comment by samreid** [comment]
Thanks for the screencast, it seems like a good plan!

**Comment by samreid** [comment]
Fixed for vertices above, I'll create a separate issue for probes.
