### ISSUE TITLE
Black box terminals disappear on Reset All

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-basics#54]
Tested on dev.6 in latest Mac OSX/Chrome. The terminals at the edge of the black box disappear if the sim is reset.

Attach components to the black box in Investigate mode.
<img width="500" alt="cf6c1efe-444d-4db2-86de-da7b7359bdaf" src="https://cloud.githubusercontent.com/assets/8419308/14416668/167e3742-ff6a-11e5-8465-ada43e187e4c.png">

Switch to Build.
<img width="500" alt="61442668-e5bd-4485-94b6-c56cd4070549" src="https://cloud.githubusercontent.com/assets/8419308/14416676/1ff23a8a-ff6a-11e5-8577-3fd907de595a.png">

Refresh all. The sim returns to Investigate mode, but the terminals on the black box have disappeared.
<img width="300" alt="8738defe-b4b0-4f1e-829b-dd61d4c0f957" src="https://cloud.githubusercontent.com/assets/8419308/14416693/3e20db9c-ff6a-11e5-8288-2ef5472ec459.png">

Switch to Investigate — still missing terminals.
<img width="300" alt="c44be9bb-ce2e-4735-8384-21a9471af25d" src="https://cloud.githubusercontent.com/assets/8419308/14416696/4f0bffa4-ff6a-11e5-9a6f-092e8fcddf0f.png">

Switch back to Investigate. The terminals have reappeared, and components can be attached.
<img width="300" alt="b0b74815-a28f-4f23-9d48-087cb1355ffc" src="https://cloud.githubusercontent.com/assets/8419308/14416698/591cdca2-ff6a-11e5-9ef6-a0fa5ecfcf6c.png">

If nothing is attached to the box while in Investigate, the terminals will still be missing from the black box in Build mode.

**Comment by samreid** [comment]
Fixed, most likely during refactoring for #16, closing.
