### ISSUE TITLE
Cannot reattach components to black box after severing connection

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-basics#55]
Observed in dev.6.

If the connection between the black box and a component is severed (by the scissors or deletion), it is impossible to reattach a component to the black box node.

The gif below shows the current in the circuit at 1.20 amps before cutting the connection to the black box. The wire is reattached (wire snaps to node, but no solder appears) but the ammeter reads 0 amps. Clicking on the node reveals an active scissors button, despite the node apparently being disconnected in the model. 

![inactive_bb_node](https://cloud.githubusercontent.com/assets/8419308/14420153/89723272-ff87-11e5-8d94-3490181e6219.gif)

**Comment by samreid** [comment]
I have reproduced this problem, thanks for the report.

**Comment by samreid** [comment]
Fixed in above commit, would be good to get tested once a new version is published.  Putting on hold until then.

**Comment by samreid** [comment]
This solution is at odds with https://github.com/phetsims/circuit-construction-kit-basics/issues/76

**Comment by samreid** [comment]
Fixed above, but this may have introduced some new issue. Black box will need significant testing.

**Comment by samreid** [comment]
Fixed here, @arouinfar can you test a variety of actions in the black box screen and see if any trouble arises?
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-basics/1.0.0-dev.8/circuit-construction-kit-basics_en.html

**Comment by arouinfar** [comment]
Fixed! Thanks @samreid.
