### ISSUE TITLE
Model of internal resistance in the wire differs from Java, does not scale with length

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-basics#56]
While in the process of discovering the Warm-up black box is a wire, I realized the internal resistance of the wires in the HTML5 sim doesn't seem to match the Java version. 

In dev.6, the internal resistance of the wire is not apparent unless the resistance in the circuit is otherwise 0. For example, a long wire in a circuit containing a 9V battery and 1 ohm resistor does not appear to have a measurable voltage drop (and therefore resistance). I would expect to see ~0.01 V for long wires, if keeping consistent with Java. Short wires may not register any voltage due to the loss of the thousandths place
![image](https://cloud.githubusercontent.com/assets/8419308/14420411/3538d5ce-ff89-11e5-9cd6-c04bfabada98.png)

If the resistor is removed, all wire segments will have the same voltage drop, regardless of the length. However, resistance should scale with length (R = rho*L/A). And in this case, the resistance of each wire segment is 2.50 V/2.91 amps = 0.86 ohms, which is way too high.
![image](https://cloud.githubusercontent.com/assets/8419308/14420656/854a6144-ff8a-11e5-800b-d972a9223e79.png)
![image](https://cloud.githubusercontent.com/assets/8419308/14420684/a7bc7884-ff8a-11e5-9c79-176745759509.png)

In Java, the internal resistance of the wire is appropriately small (~10^-4 ohms) and scales appropriately with length.
![image](https://cloud.githubusercontent.com/assets/8419308/14420340/c8bb724e-ff88-11e5-90a7-899893dfddb7.png)
![image](https://cloud.githubusercontent.com/assets/8419308/14420357/e1254198-ff88-11e5-9d77-159841e19f0f.png)
![image](https://cloud.githubusercontent.com/assets/8419308/14420748/f890a23a-ff8a-11e5-8792-25b2a52119d1.png)
![image](https://cloud.githubusercontent.com/assets/8419308/14420761/09511758-ff8b-11e5-8ed2-108bbe1b856a.png)

I'll note we may want to add the fire graphic to the HTML5 version when the circuit is shorted, though not sure it is necessary for the MVP.

**Comment by samreid** [comment]
I'm moving the fire artwork to a separate issue.

**Comment by samreid** [comment]
The Java model for resistivity is:

```
DEFAULT_RESISTIVITY = 1E-4
MIN_RESISTANCE = 1E-8
```
and a wire stretching diagonally across the screen is this long:
```
15.120675866835684
```
and the resistivity slider varies between DEFAULT_RESISTIVITY and 1.0.

The resistance = length*resistivity.

**Comment by samreid** [comment]
A wire that stretches across the screen in HTML5 is 990 screen pixels long, so we'll scale it for consistency.

**Comment by samreid** [comment]
In the above commit, wire resistivity is modeled as in the Java one.  Would be good to have @arouinfar double check the physics once a new dev version is published.  Putting on hold until then.

**Comment by samreid** [comment]
@arouinfar can you please test this version at your convenience?
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-basics/1.0.0-dev.8/circuit-construction-kit-basics_en.html

**Comment by arouinfar** [comment]
@samreid this looks good to me. Thanks!
