### ISSUE TITLE
Change Warm-up from wire to resistor

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-basics#57]
I played around quite a bit with the Warm-up black box, and have concluded that there must be a wire hiding behind the box. However, due (at least in part) to #56 the interaction felt very buggy.

I do not think the wire is an appropriate challenge to introduce students to the game, given how easy it is to create a short circuit. I think it's best for the warm-up to be a single resistor. We could either use Black Box 1 as the warm-up, and shift the numbering accordingly, or we could give the warm-up resistor a different resistance (perhaps 9 ohms).

For example, this 9V battery appears to have a voltage of 7.71V.
<img width="600" alt="screen shot 2016-04-08 at 11 58 54 am" src="https://cloud.githubusercontent.com/assets/8419308/14416770/2341e7e8-ff6b-11e5-9986-c049462c14d3.png">

Keeping the black probe on the black box's left terminal, and moving the red probe to different locations along the same wire, the voltage changes at each node -- meaning the wire must have some resistance. At each step, the voltage increases by 1.29V, so each segment apparently has the same resistance (regardless of its length).
<img width="600" alt="screen shot 2016-04-08 at 11 59 25 am" src="https://cloud.githubusercontent.com/assets/8419308/14416821/b8a91504-ff6b-11e5-96fa-fd43cf5eac04.png">
<img width="600" alt="screen shot 2016-04-08 at 11 59 39 am" src="https://cloud.githubusercontent.com/assets/8419308/14416825/b8ac0f84-ff6b-11e5-8f43-9c9cc6fe2ef5.png">
<img width="600" alt="screen shot 2016-04-08 at 11 59 42 am" src="https://cloud.githubusercontent.com/assets/8419308/14416823/b8a98354-ff6b-11e5-9b69-01f703592311.png">
<img width="600" alt="screen shot 2016-04-08 at 11 59 46 am" src="https://cloud.githubusercontent.com/assets/8419308/14416822/b8a93caa-ff6b-11e5-8b4b-f36549c4cfe3.png">
<img width="600" alt="screen shot 2016-04-08 at 11 59 58 am" src="https://cloud.githubusercontent.com/assets/8419308/14416824/b8a9c3c8-ff6b-11e5-9b8d-10bef9f52cf9.png">

**Comment by samreid** [comment]
Fixed as described above, closing.
