### ISSUE TITLE
Investigate sensitivity of voltmeter probes

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-basics#58]
@kathy-phet reported that

> The Voltage meter probes are buggy on my machine. The positioning of where to place to get a readout is odd ... eg the needle of the probe is off the wire but the handle is on and it reads. But it doesn't read when the probe itself is touching the wire.

Oh my machine (latest Mac/Chrome), the probes seem fairly forgiving. The tip of the probes is not exactly on the node, but still reads.
![image](https://cloud.githubusercontent.com/assets/8419308/14421657/0d26632e-ff90-11e5-88a2-e9e4fd0ce50e.png)

However, I am unable to get a reading when the probe is centered on a vertical wire, though it works fine for horizontal wires.
![image](https://cloud.githubusercontent.com/assets/8419308/14421698/4ab0af24-ff90-11e5-94ca-eb8fca2356d4.png)
![image](https://cloud.githubusercontent.com/assets/8419308/14421703/53a93f74-ff90-11e5-9335-df1824a506a0.png)

**Comment by samreid** [comment]
I put a debug shape on the hit area for wire and black dot on the red vertex.  This is reporting a hit even though it is far from the hit area:

![image](https://cloud.githubusercontent.com/assets/679486/14796303/e53619b2-0ae9-11e6-9666-637856dd3042.png)

**Comment by samreid** [comment]
Testing whether this could be a kite bug: the problem is still there if I use square caps.

**Comment by samreid** [comment]
The probe was incorrectly using the top-left of the bounding box of the probe instead of the top center.

**Comment by samreid** [comment]
Fixed above, closing.

**Comment by samreid** [comment]
Let's leave this open for testing.  On hold until a new version is published.

**Comment by samreid** [comment]
Fixed as described above, @arouinfar can you please verify?
http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-basics/1.0.0-dev.8/circuit-construction-kit-basics_en.html

**Comment by arouinfar** [comment]
Probe sensitivity is spot-on in dev.8. Closing!
