### ISSUE TITLE
"Build a Circuit that behaves the same way" gets overlapped

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-basics#61]
If you build a circuit around the black box and avoid the "what is in the black box" text, it will lead to putting components beneath the black box (because the "what is" text is above the black box), then when it shows the "Build a circuit that behaves the same way", that text gets obscured like so:

![image](https://cloud.githubusercontent.com/assets/679486/14570249/8bf50c32-0300-11e6-9002-8bbb36d4aeb2.png)

Perhaps we should put both messages in the same spot?

Also a reminder that if PhET publishes a black box version on our website, we could have a multiple choice response as a scaffolding toward creating black boxes, so this decision is primarily for Stanford.

**Comment by arouinfar** [comment]
@samreid yes, let's move the "Build a circuit that behaves the same way." text up to the top so it doesn't get obscured.

**Comment by samreid** [comment]
Fixed, closing.
