### ISSUE TITLE
Voltage reading on wire should be proportionate to distance across wire (like potentiometer).

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-basics#65]
Similar to #56 the voltage should drop proportionately to length across the wire.

**Comment by samreid** [comment]
Fixed, looks like this:

![image](https://cloud.githubusercontent.com/assets/679486/14797304/524b1b4c-0aef-11e6-877c-65e56cc68673.png)

Should be tested by @arouinfar in next published version, putting on hold until then.

**Comment by samreid** [comment]
@arouinfar can you please test this version?

http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-basics/1.0.0-dev.8/circuit-construction-kit-basics_en.html

**Comment by arouinfar** [comment]
Looks great @samreid! Closing.
