### ISSUE TITLE
Simplify Matrix Math

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-basics#66]
From a TODO, I have this code:

```js
updateNodeTransform: function( contentNode, startPosition, endPosition, contentScale ) {
      var angle = endPosition.minus( startPosition ).angle();
      // TODO: Simplify this matrix math.
      contentNode.resetTransform();
      contentNode.mutate( {
        scale: contentScale
      } );
      contentNode.rotateAround( new Vector2( 0, 0 ), angle );
      contentNode.x = startPosition.x;
      contentNode.y = startPosition.y;
    }
```

Would it be better to create a single Matrix and set in one step?  Or is the above code good because scenery batches transforms?  @jonathanolson what would you recommend here?

**Comment by jonathanolson** [comment]
The fastest code would probably have a persistent scratch matrix which is set it one step, and be something like:
```js
var cos = Math.cos( angle );
var sin = Math.sin( angle );
contentNode.setMatrix( scratchMatrix.rowMajor(
  cos * contentScale, -sin * contentScale, startPosition.x,
  sin * contentScale, cos * contentScale, startPosition.y,
  0, 0, 1
) );
```

For more readability, you can compose operations on the matrix:
```js
scratchMatrix.setToScale( contentScale ).multiplyMatrix( scratchMatrix2.setToRotationZ( angle ) ).multiplyMatrix( scratchMatrix2.setToTranslation( startPosition.x, startPosition.y ) );
```

Scenery does do some non-batched work when making those changes, so it's generally a bit more ideal to do it once (particularly if you are under a bounds listener).

That said, you could also just consolidate the position setter into:
```js
contentNode.translation = startPosition;
```
and your scale setter into:
```js
contentNode.scale( contentScale );
```
and your rotation setter into:
```js
contentNode.rotate( angle );
```
and leave it (and test performance).

**Comment by samreid** [comment]
This is non-critical for MVP, so I'll deprioritize.

**Comment by samreid** [comment]
Fixed using scratch matrices and working nicely, thanks @jonathanolson!
