### ISSUE TITLE
Credits for QA team

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-basics#70]
From #60, we need to add credits for the QA team.  @ariel-phet would you like to give a prospective list now or wait until we are closer to testing?

**Comment by ariel-phet** [comment]
Steele, Bryce, Ben, Elise

**Comment by samreid** [comment]
I put the QA credits as Steele Dalton, Bryce Griebenow, Elise Morgan, Ben Roberts, can you check the last names and close if correct?

**Comment by ariel-phet** [comment]
Correct
