### ISSUE TITLE
Deleting a circuit element connected to a black box interface vertex from the inside deletes the vertex

### ISSUE THREAD

**Issue by samreid** [phetsims/circuit-construction-kit-basics#76]
![image](https://cloud.githubusercontent.com/assets/679486/14791812/b6d8386c-0ad4-11e6-9177-6a4de750eb0e.png)

**Comment by samreid** [comment]
Fixed above, but this may have introduced some new issue. Black box will need significant testing.

**Comment by samreid** [comment]
@arouinfar can you test this specific behavior in the latest version?

http://www.colorado.edu/physics/phet/dev/html/circuit-construction-kit-basics/1.0.0-dev.8/circuit-construction-kit-basics_en.html

**Comment by arouinfar** [comment]
I haven't been able to reproduce this in dev.8 @samreid. Closing.
