### ISSUE TITLE
Assets needed for development

### ISSUE THREAD

**Issue by arouinfar** [phetsims/circuit-construction-kit-basics#9]
Since @samreid will be beginning development on this soon, we should get the assets in order.

@arouinfar will send the following assets to @samreid 
- [x] Body of voltmeter
- [x] Probes of voltmeter
- [x] Body of ammeter
- [x] Ammeter probe
- [x] Battery
- [x] Resistor

These components will be drawn in code
- Light bulb - common component used in Faraday's Law
- Light bulb glow - linear glow like Acid-Base Solutions (not the halo)
- Wires with gradient

@samreid please feel free to edit this comment if there are any additional items needed.

**Comment by arouinfar** [comment]
It looks like some of these assets have already been committed to the repo.
![image](https://cloud.githubusercontent.com/assets/8419308/13304467/068e203a-db12-11e5-9686-db194d43c8e9.png)

@samreid please use battery_variable_v.ai for CCK: Black Box and disregard the wire_segment.ai. I will be sending the remaining assets to you shortly.

**Comment by arouinfar** [comment]
The remaining assets have been emailed to @samreid. 

The asset for the resistor does not have the colored stripes or wire, as I imagine these will need to be generated in code.

**Comment by samreid** [comment]
> The asset for the resistor does not have the colored stripes or wire, as I imagine these will need to be generated in code.

Yes, I'll generate this in the code.

> disregard the wire_segment.ai.

I'll delete it.

**Comment by samreid** [comment]
Thanks @arouinfar I think we are good to go, closing.
